
import { NCRRecord } from './types';

export const SAMPLE_DATA: NCRRecord[] = [
  {
    "NCMR": "0014962",
    "DATE": "08/27/25",
    "Date NC was Flagged": "08/27/25",
    "Time NC was Flagged": "7:30:00 AM",
    "Priority Status": "Standard",
    "Discovery Area": "Subassembly",
    "Part No.": "AM-2079-1400",
    "Part Description": "MOUNTING PLATE",
    "QTY of Defected Parts": "8",
    "Purchase Order No.": "118650",
    "Source Simplified": "AGST",
    "Source": "AGST - THAILAND",
    "Job No. or GL No.": "1220",
    "Type of Defect": "Dimensional",
    "Issuing Inspector Stamp No.": "110",
    "Disposition": "RWK",
    "Containment Required? (Y/N)": "",
    "Containment Completed?": "",
    "RTV Status": "",
    "Scrap Cost": "",
    "Rework WOR No.": "R15183",
    "Actions / Comments": "Released to Stores",
    "Date Dispositioned in Global Shop": "9/2/2025",
    "Date Closed": "09/22/25"
  },
  {
    "NCMR": "0014973",
    "DATE": "08/28/25",
    "Date NC was Flagged": "08/28/25",
    "Time NC was Flagged": "2:39:00 PM",
    "Priority Status": "Urgent",
    "Discovery Area": "Receiving Inspection",
    "Part No.": "AM-1928-A44",
    "Part Description": "ADJ FWD BOOTSTRAP",
    "QTY of Defected Parts": "2",
    "Purchase Order No.": "134373",
    "Source Simplified": "Supplier",
    "Source": "GEMBA AUTOMATION LLC",
    "Job No. or GL No.": "1220",
    "Type of Defect": "Multiple",
    "Issuing Inspector Stamp No.": "222",
    "Disposition": "RWK",
    "Containment Required? (Y/N)": "",
    "Containment Completed?": "",
    "RTV Status": "",
    "Scrap Cost": "",
    "Rework WOR No.": "R15144",
    "Actions / Comments": "Released to Stores",
    "Date Dispositioned in Global Shop": "8/29/2025",
    "Date Closed": "09/17/25"
  },
  {
    "NCMR": "0015054",
    "DATE": "09/22/25",
    "Date NC was Flagged": "09/19/25",
    "Time NC was Flagged": "2:00:00 PM",
    "Priority Status": "Standard",
    "Discovery Area": "Receiving Inspection",
    "Part No.": "AGSE-C05208-P03",
    "Part Description": "CYLINDER CLEVIS",
    "QTY of Defected Parts": "15",
    "Purchase Order No.": "134170",
    "Source Simplified": "AGST",
    "Source": "AGST - THAILAND",
    "Job No. or GL No.": "134170",
    "Type of Defect": "Surfaces",
    "Issuing Inspector Stamp No.": "323",
    "Disposition": "Mixed",
    "Containment Required? (Y/N)": "Y",
    "Containment Completed?": "Y",
    "RTV Status": "",
    "Scrap Cost": "",
    "Rework WOR No.": "R15307",
    "Actions / Comments": "Partial rework required, split into scrap and RWK units.",
    "Date Dispositioned in Global Shop": "9/22/2025",
    "Date Closed": "10/09/25"
  }
];
